# Generated by Django 5.2 on 2025-09-19 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_remove_book_bookid_book_issued_book_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='bookid',
        ),
    ]
